# Variability hypothesis 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from scipy.optimize import fsolve
from scipy import special

In [3]:
sig1, sig2, pA = 1, 2, 0.25

In [6]:
def next_gen_beta(beta):
    def helpf(x):
        return beta*special.erfc(x/(np.sqrt(2)*sig1))+ (
            (1-beta)*special.erfc(x/(np.sqrt(2)*sig2)))-1+2*pA
    starting_guess = (sig1+sig2)/2
    c_star=  fsolve(helpf, starting_guess)
    return (beta/pA)*(1/2- 1/2*special.erfc(c_star/(np.sqrt(2)*sig1))), c_star

In [7]:
next_gen_beta(0.5)

(array([0.64425763]), array([0.92350831]))

In [8]:
next_gen_beta(0.64425763)

(array([0.7693364]), array([0.83640342]))

In [9]:
next_gen_beta(0.7693364)

(array([0.86138717]), array([0.77189737]))

In [10]:
next_gen_beta(0.86138717)

(array([0.92102072]), array([0.73000821]))